openapi: "3.0.0"
info:
  title: "Summers SNS 서비스 API"
  description: >
    서머즈 SNS 서비스의 API 테스트를 위해 작성된 문서입니다.
  version: "1.0.0"

servers:
  - url: "http://localhost:8080/api"
    description: "개발 전용 서버"

tags:
  - name: auth
    description: 🔰 인증 및 인가에 관한 API
  - name: user
    description: 😁 사용자에 관한 API
  - name: test
    description: ⚠ 테스트를 위한 API
paths:

  /auth/credentials:
    post:
      summary: "사용자 인증 정보를 생성하여 저장합니다."
      description: |+
        이메일 또는 번호를 제공받아 사용자 인증 정보를 생성합니다.
        둘 중, 한 정보는 필수입니다.
      tags:
        - auth
      requestBody:
        description: "사용자 인증 정보를 사용하기 위한 요청 정보"
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - type: string
                - type: integer
            example:
                폰 번호 생성 예시:
                  phone: "01033334444"
                이메일 생성 예시:
                  email: "your email"
      responses:
        201:
          description: "정보 생성 완료, 생성된 인증 정보의 id를 반환합니다."
          content:
            appplication/json:
              schema:
                type: object
                properties:
                  createdCredentialsId:
                    type: integer
                    description: "생성된 인증 정보의 ID"
        409:
          description: |+
            이미 존재하는 정보가 있음을 의미합니다
            인증 코드를 다시 해당 유저 인증 정보로 발송합니다.
          content:
            appplication/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "인증 정보 재발송 정보 메시지"
        422:
          description: "잘못된 폼 요청 정보"
          content:
            appplication/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /auth/sms:
    post:
      summary: "지정된 이메일 또는 폰 번호로 보안코드를 전송합니다."
      description: |+
        보안 코드는 6자리 입니다.
      tags:
        - auth
      requestBody:
        description: "폰 또는 이메일 정보"
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - type: string
                - type: integer
            example:
              폰 정보 예시:
                phone: "01033334444"
              이메일 정보 예시:
                email: "your email"
      responses:
        422:
          description: "잘못된 폼 요청 정보"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        200:
          description: "인증 코드 발송 성공"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "인증번호 발송 메시지"

  /auth/sms/verify:
    post:
      summary: "인증코드를 검사하고 성공 여부를 데이터베이스에 등록합니다."
      description: |+
        인증 코드를 검사 후, 성공 시 데이테베이스에 성공 여부를 등록하고 성공 메시지를 반환합니다.
        실패 시, 실패 코드와 함께 메시지를 반환홥니다.
      tags:
        - auth
      requestBody:
        summary: "폰 번호 혹은 이메일 정보와 인증 코드"
        required: true
        content:
          application/json:
            schema:
              type: object
            example:
              폰 정보 예시:
                phone: "01033334444"
                code: 010010
              이메일 정보 예시:
                email: "your email"
                code: 010010
      responses:
        200:
          description: "인증 코드 검사 성공"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "인증코드 검사 성공 메시지"
        422:
          description: "인증 정보 또는 인증 코드 정보가 등록되어 있지 않음"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        400:
          description: "인증코드가 잘못되었습니다."
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string


  /auth/login:
    post:
      summary: "로그인을 수행합니다."
      description: |+
        유저 정보와 비밀번호 정보를 받아서 로그인을 수행합니다.
        로그인에 성공한다면 session 에 대한 cookie 값을 설정합니다.
      tags:
        - auth
      requestBody:
        description: "이메일 또는 폰 번호와 비밀번호 정보"
        required: true
        content:
          application/json:
            schema:
              type: object
            example:
              번호 예시:
                phone: "01011112222"
                password: "password"
              이메일 예시:
                email: "your email"
                password: "password"
      responses:
        200:
          description: "로그인 성공"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        401:
          description: "비밀번호 불일치"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        429:
          description: "잘못된 폼 요청 정보"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /test/auth/credentials:
    post:
      summary: "사용자 인증 정보를 생성하여 저장합니다."
      description: |+
        인증 정보 생성을 테스트합니다.
        ⚠ 기존 API 와 달리 인증정보를 발송하지 않습니다. ⚠
      tags:
        - test
      requestBody:
        description: "사용자 인증 정보를 사용하기 위한 요청 정보"
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - type: string
                - type: integer
            example:
              폰 번호 테스트 예시:
                phone: "01033334444"
                isTest: true
              이메일 테스트 예시:
                email: "your email"
                isTest: true

      responses:
        201:
          description: "정보 생성 완료, 생성된 인증 정보의 id를 반환합니다."
          content:
            appplication/json:
              schema:
                type: object
                properties:
                  createdCredentialsId:
                    type: integer
                    description: "생성된 인증 정보의 ID"
        409:
          description: |+
            이미 존재하는 정보가 있음을 의미합니다
            인증 코드를 다시 해당 유저 인증 정보로 발송합니다.
          content:
            appplication/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "인증 정보 재발송 정보 메시지"
        422:
          description: "잘못된 폼 요청 정보"
          content:
            appplication/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
